# Cloudflare Pages configuration
name = "question-bank-frontend"
compatibility_date = "2024-01-01"

[env.production.vars]
VITE_API_URL = "https://question-bank-api.your-subdomain.workers.dev"

[env.preview.vars]
VITE_API_URL = "https://question-bank-api.your-subdomain.workers.dev"