name = "question-bank-api"
main = "src/index.js"
compatibility_date = "2024-01-01"
compatibility_flags = ["nodejs_compat"]

[[kv_namespaces]]
binding = "QUESTIONS_KV"
id = "questions_kv_namespace"
preview_id = "questions_kv_preview"

[[d1_databases]]
binding = "DB"
database_name = "question-bank-db"
database_id = "question-bank-db-id"

[vars]
JWT_SECRET = "your-jwt-secret-key"
GOOGLE_CLIENT_ID = "your-google-client-id"
FRONTEND_URL = "https://question-bank.pages.dev"